exports.cityList = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

exports.provinceList = [
    {
        'sn':'京',
        'name':'北京',
        "codes":'ABCEFGO'
    },{
        'sn':'津',
        'name':'天津',
        "codes":'ABCDE'
    },{
        'sn':'渝',
        'name':'重庆',
        "codes":'ABCFGH'
    },{
        'sn':'沪',
        'name':'上海',
        "codes":'ABCD'
    },{
        'sn':'冀',
        'name':'河北',
        "codes":'ABCDEFGHJRT'
    },{
        'sn':'晋',
        'name':'山西',
        "codes":'ABCDEFGHJKLM'
    },{
        'sn':'辽',
        'name':'辽宁',
        "codes":'ABCDEFGHJKLMNPV'
    },{
        'sn':'吉',
        'name':'吉林',
        "codes":'ABCDEFGHJ'
    },{
        'sn':'黑',
        'name':'黑龙江',
        "codes":'ABCDEFGHJKLMNPR'
    },{
        'sn':'苏',
        'name':'江苏',
        "codes":'ABCDEFGHJKLMN'
    },{
        'sn':'浙',
        'name':'浙江',
        "codes":'ABCDEFGHJKL'
    },{
        'sn':'皖',
        'name':'安徽',
        "codes":'ABCDEFGHJKLMNPQR'
    },{
        'sn':'闽',
        'name':'福建',
        "codes":'ABCDEFGHJKO'
    },{
        'sn':'赣',
        'name':'江西',
        "codes":'ABCDEFGHJKL'
    },{
        'sn':'鲁',
        'name':'山东',
        "codes":'ABCDEFGHJKLMNPQRU'
    },{
        'sn':'豫',
        'name':'河南',
        "codes":'ABCDEFGHJKLMNPQRSU'
    },{
        'sn':'鄂',
        'name':'湖北',
        "codes":'ABCDEFGHJKLMNPQ'
    },{
        'sn':'湘',
        'name':'湖南',
        "codes":'ABCDEFGGHJKLMNP'
    },{
        'sn':'粤',
        'name':'广东',
        "codes":'ABCDEFGHJKLMNPQRSTUVWXYZ'
    },{
        'sn':'琼',
        'name':'海南',
        "codes":'ABCDE'
    },{
        'sn':'川',
        'name':'四川',
        "codes":'ABCDEFHJKLMNQRSTUVWXYZ'
    },{
        'sn':'贵',
        'name':'贵州',
        "codes":'ABCDEFGHJ'
    },{
        'sn':'云',
        'name':'云南',
        "codes":'ABCDEFGHJLKMNPQRS'
    },{
        'sn':'陕',
        'name':'陕西',
        "codes":'ABCDEFGHJKU'
    },{
        'sn':'甘',
        'name':'甘肃',
        "codes":'ABCDEFGHJKLMNP'
    },{
        'sn':'青',
        'name':'青海',
        "codes":'ABCDEFGH'
    },{
        'sn':'蒙',
        'name':'内蒙古',
        "codes":'ABCDEFGHJKL'
    },{
        'sn':'桂',
        'name':'广西',
        "codes":'ABCDEFGHJKMLNP'
    },{
        'sn':'宁',
        'name':'宁夏',
        "codes":'ABCDE'
    },{
        'sn':'新',
        'name':'新疆',
        "codes":'ABCDEFGHJKLMNPQR'
    },{
        'sn':'藏',
        'name':'西藏',
        "codes":'ABCDEFGHO'
    }
];